import type { CrmState } from './types';

export const SEED: CrmState = {
  cars: [
    {
      id: 'lx600',
      brand: 'Lexus', model: 'LX 600', year: 2024,
      country: 'jp', mileage: '12 000 км', body: 'SUV', drive: 'AWD',
      fuel: 'Бензин', transmission: 'Автомат',
      price: '14 800 000 ₽', priceLocal: '¥ 21,400,000',
      badges: ['В пути', 'Premium'],
      accent: 'coral',
      eta: 'Доставка 28 апр.',
      spec: '3.5 V6 · 415 л.с. · 4WD',
      img: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200&q=80',
    },
    {
      id: 'gv80',
      brand: 'Genesis', model: 'GV80', year: 2024,
      country: 'kr', mileage: '8 400 км', body: 'SUV', drive: 'AWD',
      fuel: 'Бензин', transmission: 'Автомат',
      price: '8 950 000 ₽', priceLocal: '₩ 96,000,000',
      badges: ['В наличии'],
      accent: 'cyan',
      eta: 'На складе во Владивостоке',
      spec: '3.5T · 380 л.с. · AWD',
      img: 'https://images.unsplash.com/photo-1631295868223-63265b40d9e4?auto=format&fit=crop&w=1200&q=80',
    },
    {
      id: 'lc500',
      brand: 'Lexus', model: 'LC 500', year: 2023,
      country: 'jp', mileage: '24 000 км', body: 'Coupe', drive: 'RWD',
      fuel: 'Бензин', transmission: 'Автомат',
      price: '11 200 000 ₽', priceLocal: '¥ 16,200,000',
      badges: ['Auction Grade 4.5'],
      accent: 'coral',
      eta: 'Аукцион 12 мая',
      spec: '5.0 V8 · 477 л.с.',
      img: 'https://images.unsplash.com/photo-1617469767053-d3b523a0b982?auto=format&fit=crop&w=1200&q=80',
    },
    {
      id: 'l9',
      brand: 'Li', model: 'L9 Max', year: 2024,
      country: 'cn', mileage: '6 200 км', body: 'SUV', drive: 'AWD',
      fuel: 'Гибрид', transmission: 'Автомат',
      price: '6 480 000 ₽', priceLocal: '¥ 469,800',
      badges: ['Гибрид'],
      accent: 'cyan',
      eta: 'В пути · Хоргос',
      spec: '1.5T + EV · 449 л.с.',
      img: 'https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?auto=format&fit=crop&w=1200&q=80',
    },
    {
      id: 'm5',
      brand: 'BMW', model: 'M5 Competition', year: 2023,
      country: 'kr', mileage: '18 500 км', body: 'Sedan', drive: 'AWD',
      fuel: 'Бензин', transmission: 'Автомат',
      price: '13 600 000 ₽', priceLocal: '₩ 145,000,000',
      badges: ['Под заказ'],
      accent: 'coral',
      eta: 'Срок: 35–45 дней',
      spec: '4.4 V8 · 625 л.с.',
      img: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80',
    },
    {
      id: 'gle53',
      brand: 'Mercedes-AMG', model: 'GLE 53', year: 2024,
      country: 'jp', mileage: '11 000 км', body: 'SUV', drive: 'AWD',
      fuel: 'Бензин', transmission: 'Автомат',
      price: '12 100 000 ₽', priceLocal: '¥ 17,800,000',
      badges: ['В пути'],
      accent: 'cyan',
      eta: 'Прибытие 5 мая',
      spec: '3.0 R6 · 435 л.с.',
      img: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=1200&q=80',
    },
  ],

  timeline: [
    { id: 't1', code: '01', title: 'Заявка', sub: 'Звонок, мессенджер или анкета — 5 минут.', dur: 'День 0' },
    { id: 't2', code: '02', title: 'Подбор', sub: 'Алексей в Корее, Денис в России — закрытые источники, аукционы, дилерские склады.', dur: 'Дни 1–7' },
    { id: 't3', code: '03', title: 'Проверка', sub: 'Видео-осмотр, проверка VIN, история, юр. чистота. Никаких скрытых дефектов.', dur: 'Дни 5–10' },
    { id: 't4', code: '04', title: 'Покупка', sub: 'Договор, прозрачная смета, фиксация курса. Без переплат.', dur: 'День 10' },
    { id: 't5', code: '05', title: 'Доставка', sub: 'Логистика, таможня, СБКТС, ЭПТС — всё на нас. Отслеживание онлайн.', dur: 'Дни 14–45' },
    { id: 't6', code: '06', title: 'Передача', sub: 'Предпродажная подготовка, ключи в руки у вашего подъезда.', dur: 'День X' },
  ],

  faq: [
    { id: 'f1', q: 'Сколько занимает доставка из Кореи / Японии / Китая?', a: 'Корея — 14–25 дней с момента покупки. Япония — 25–35 дней (зависит от аукциона). Китай — 30–45 дней через Хоргос. Сроки фиксируем в договоре.' },
    { id: 'f2', q: 'Что входит в цену "под ключ"?', a: 'Стоимость авто, аукционный сбор, фрахт, страхование при перевозке, таможенная очистка, утилизационный сбор, СБКТС и ЭПТС, доставка по РФ. Никаких "сюрпризов" в финале.' },
    { id: 'f3', q: 'Как защититься от "перебитых" авто?', a: 'Каждый автомобиль проходит проверку по VIN в национальных базах (Carfax/AutoCheck/Encar/USS), осмотр нашим инспектором с фото и видео, и дополнительный контроль перед отгрузкой. Если что-то всплыло — сделка отменяется без потерь для вас.' },
    { id: 'f4', q: 'Можно ли в кредит или лизинг?', a: 'Да. Работаем с банками-партнёрами и лизинговыми компаниями. Одобрение — за 1–2 дня, ставки от 14,9%. Trade-in вашего авто тоже возможен.' },
    { id: 'f5', q: 'А если мне не понравится?', a: 'До покупки на аукционе/у дилера — отменяем без потерь. После — действует гарантия на скрытые дефекты, заявленные в документах продавца. Все спорные ситуации фиксируем в договоре заранее.' },
    { id: 'f6', q: 'Как происходит оплата?', a: 'Поэтапно: бронь, оплата авто, оплата логистики и пошлин. Все платежи — на расчётный счёт ООО, с закрывающими документами. Никаких "чёрных" касс и крипты.' },
  ],

  reviews: [
    { id: 'r1', name: 'Артём К.', city: 'Москва',     car: 'Lexus LX 600 · 2024', text: 'Привезли LX из Японии за 31 день. Видео-осмотр на аукционе, всё показали — днище, движок, салон. Цена в финале даже на 80 тыс. ниже, чем смета. Рекомендую.',                 rating: 5, avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80', date: '24 апр. 2026', platform: 'yandex' },
    { id: 'r2', name: 'Юлия М.',  city: 'СПб',        car: 'Genesis GV80 · 2024', text: 'Долго выбирала между GV80 и X5. Денис разложил по полочкам стоимость владения — и сэкономил мне ~1,2 млн против дилера. Машина приехала в идеале.',                            rating: 5, avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80', date: '20 апр. 2026', platform: 'avito'  },
    { id: 'r3', name: 'Сергей В.', city: 'Краснодар',  car: 'BMW M5 Competition',  text: 'Заказывал M5 в макс. комплектации. Парни нашли вариант с Гранд Корея за 2 недели, привезли в Краснодар через 38 дней. Документы — чистые, ЭПТС оформили без проблем.', rating: 5, avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80', date: '18 апр. 2026', platform: 'autoru' },
  ],

  inTransit: [
    { id: 'it-bmw-x5',       brand: 'BMW',          model: 'X5 xDrive40i', country: 'kr', status: 'in-transit', statusLabel: 'В пути',         eta: '14 дней',  priceLandedRu: '7 800 000 ₽',  accent: 'coral', img: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1200&q=80' },
    { id: 'it-lexus-lx',     brand: 'Lexus',        model: 'LX 600',       country: 'jp', status: 'customs',    statusLabel: 'На таможне',     eta: '5 дней',   priceLandedRu: '12 400 000 ₽', accent: 'cyan',  img: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200&q=80' },
    { id: 'it-mercedes-g63', brand: 'Mercedes-AMG', model: 'G63',          country: 'kr', status: 'in-transit', statusLabel: 'В пути',         eta: '21 день',  priceLandedRu: '21 900 000 ₽', accent: 'coral', img: 'https://images.unsplash.com/photo-1542362567-b07e54358753?auto=format&fit=crop&w=1200&q=80' },
    { id: 'it-genesis-gv80', brand: 'Genesis',      model: 'GV80 3.5T',    country: 'kr', status: 'ready',      statusLabel: 'Готов к выдаче', eta: 'на руках', priceLandedRu: '6 600 000 ₽',  accent: 'cyan',  img: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80' },
  ],

  feed: [
    { id: 'feed1', time: '2 мин назад', text: 'Lexus LX 600 — выгружен во Владивостоке', icon: 'truck' },
    { id: 'feed2', time: '14 мин назад', text: 'Genesis GV80 — VIN-проверка пройдена', icon: 'shield' },
    { id: 'feed3', time: '38 мин назад', text: 'BMW M5 — выкуплен на аукционе HAA Kobe', icon: 'sparkle' },
    { id: 'feed4', time: '1 ч назад', text: 'Li L9 — таможенное оформление завершено', icon: 'doc' },
    { id: 'feed5', time: '2 ч назад', text: 'Mercedes GLE 53 — отправлен из Йокогамы', icon: 'truck' },
  ],

  settings: {
    liveCount: '47',
    totalDelivered: 1840,
    yearsOnMarket: 19,
    avgDeliveryDays: 28,
    satisfactionPct: 99,
    phone: '+7 (999) 999-99-99',
    email: 'dvapro@gmail.com',
    telegram: 'https://t.me/dvapro',
    whatsapp: 'https://wa.me/79999999999',
    cities: 'Владивосток · Москва · Сеул',
    founderRu: { name: 'Денис', surname: 'Сахаров', bio: 'Бывший Сбер. Финансы, договоры, логистика — ваш контакт в России.' },
    founderKr: { name: 'Алексей', surname: 'Старовойтов', bio: 'С 2005 года в корейском авто-рынке. Аукционы, дилеры, проверка на месте.' },
    brandQuote: 'Свои ребята — это те, на кого можно положиться в незнакомом месте, где доверять больше некому. Каждый клиент для нас — не сделка, а возможность изменить жизнь, дав машину, о которой давно мечталось.',
  },

  leads: [],
};
